### ISSUE TITLE
Is it necessary to set volume access mode with the value ReadWriteMany ?

### ISSUE THREAD

**Issue by rodjjo** [milvus-io/milvus-helm#100]
I was configuring this chart to run on a cluster kubernetes (kops) at amazon and when I configure the volume with:

```yaml
persistence:
  mountPath: "/var/lib/milvus/db"
  ## If true, alertmanager will create/use a Persistent Volume Claim
  ## If false, use emptyDir
  ##
  enabled: true
  annotations: {}
  #  helm.sh/resource-policy: keep
  persistentVolumeClaim:
    existingClaim: ""
    ## milvus data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "gp2"
    accessModes: ReadWriteOnce
    size: 50Gi
    subPath: ""
```

I get the result (No error message):
```text
    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Milvus Release version: v0.10.0, built at 2020-06-15 14:51.51, with OpenBLAS library.
You are using Milvus CPU edition
Last commit id: 5f3c0052478a08d07d68c5dc1aab57a42293f430

Loading configuration from: ../conf/server_config.yaml
Supported CPU instruction sets: avx2, sse4_2
FAISS hook AVX2
Milvus server started successfully!
Milvus server is going to shutdown ...
``` 

if I leave the defaults configuration of the chart i got no problem, but if the pod is recreated i lost the data.
