### ISSUE TITLE
Can't deploy Milvus on GPU via Kubernetes

### ISSUE THREAD

**Issue by eedmiston** [milvus-io/milvus-helm#150]
I've been trying to get Milvus (0.10.2) to run on GPU in a kubernetes installation.  It is running on the correct nodepool, but milvus stays in CrashLoopBack with the `error /var/lib/milvus/bin/milvus_server: error while loading shared libraries: /lib64/libnvidia-ml.so.1: file too short`. Here's the values.yaml I'm using:

```
nodeSelector:
  cloud.google.com/gke-nodepool: ai-gpu2
tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"
​
gpu:
  enabled: true
​
image:
  repository: milvusdb/milvus
  tag: 0.10.2-gpu-d081520-8a2393
  pullPolicy: Always
​
resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1
```
I've tried this with all of the 0.10.x versions with the same outcome.
