### ISSUE TITLE
Configurate storageClass in value.yaml, but not rendered in pvc.yaml

### ISSUE THREAD

**Issue by lordofdou** [milvus-io/milvus-helm#227]
We install the milvus through the Helm with a local value.yaml file including items as following

```yaml
cluster:
  enabled: true
minio:
  enabled: false
pulsarStandalone:
  persistence:
    storageClass: milvus-pulsar
    size: 100Gi
etcd:
  persistence:
    storageClass: milvus-ectd
    size: 20Gi
```

PVs named *milvus-pulsar* and  *milvus-ectd* have been created in manual before. Two PVCs for the pulsar and etcd are created by Helm, but there is no **storageClassName** items in their yaml file. Just like this
```yaml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
 # "storageClassName: milvus-etcd" Normally, we expected a storageClassName here
...
```

Whether the value.yaml is incorrect, or it is a bug undiscovered.
