### ISSUE TITLE
Optimization: Unify the labels of dependencis

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/milvus-helm#292]
The labels we used to manage milvus dependencies charts are different.
Let's considering about using a unified label for easier management. @LoveEachDay @Bennu-Li 

For example, the milvus release `benchmark-no-clean-cs79g-1`, we got:

labels for etcd as:
``` yaml
labels:
    app.kubernetes.io/instance: benchmark-no-clean-cs79g-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
```

labels for pulsar as:
``` yaml
labels:
    app: minio
    release: benchmark-no-clean-cs79g-1
```

labels for minio as:
``` yaml
labels:
    app: pulsar
    component: bookkeeper
    release: benchmark-no-clean-cs79g-1
```
