### ISSUE TITLE
CACHE_SIZE is set weirdly high for all deployments

### ISSUE THREAD

**Issue by datenhahn** [milvus-io/milvus-helm#355]
Hi,

the cache_size is set in the charts to:

https://github.com/milvus-io/milvus-helm/blob/master/charts/milvus/templates/querycoord-deployment.yaml#L64
```
        - name: CACHE_SIZE
          valueFrom:
            resourceFieldRef:
              divisor: 1Gi
              resource: limits.memory
```

In the default Config it says:

https://github.com/milvus-io/milvus/blob/master/configs/milvus.yaml#L164

"The `cacheSize` must be less than system memory size."

As the helm-chart sets the memory to the absolutely maximum of memory a pod can ever request (the limit) I am wondering if this can hurt milvus stability. Or is this fine and the comment in the default config needs to be adjusted instead?
