### ISSUE TITLE
Issue to deploy on GCP (ingress and persistent storage)

### ISSUE THREAD

**Issue by jplu** [milvus-io/milvus-helm#395]
Hi,

I'm trying to deploy a Milvus cluster into GCP. When I follow the GCP tutorial available at https://milvus.io/docs/gcp.md, I don't see any information about using the GCE ingress and storage disks already created. What I would like to do is the following:
* For ingress:
  * Have an ingress with the following annotations:
    ```
    kubernetes.io/ingress.global-static-ip-name: <IP-NAME>
    ingress.gcp.kubernetes.io/pre-shared-cert: <CERTIFICATE-NAME>
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
    ```
    but when I add these annotations the service becomes unavailable and GCP tells me that there is a communication issue between the created loadbalancer and the service. Maybe because of the GRPC protocol? FYI `<IP-NAME>` and `<CERTIFICATE-NAME>` are resources that have already been created.
* For persistent storage:
  * I have a persistent disk that has already been created and I would like to use it as data storage. I usually use the `gcePersistentStorage` as stated in the K8S documentation (https://kubernetes.io/fr/docs/concepts/storage/volumes/) but I don't know what I have to update in the `values.yaml` file to make Milvus use this property.

Thanks a lot in advance for any help you can give.

**Comment by haorenfsa** [comment]
@jplu  Hi, thank you for the feedback. 

First about the Ingress: 

I just checked the steps in the  https://milvus.io/docs/gcp.md. You're right about the GRPC protocol. In the document, it uses  a service to create a loadbalancer. And that loadbalancer works in  Layer 4 (TCP/IP), and doesn't bother with application protocol (which is in Layer 7). You can try using a service instread. 

If you still want to use a layer 7 loadbalancer. Many extra configurations has to be
introduced. You'll have to configure the backend protocol to http2. And create a custom `HealthCheck` Resource in GCP in order to do the correct healthcheck.
I'm just trying to write a doc about how to use gce ingress. I'll paste a link about all the detail configuration pieces here later.


And for the Persistent storage:

Did you create a resource in the kubernetes  for you persistent disk?
If so, which kind of resource did you create in the kubernetes  for you persistent disk?  A PVC(PersistentVolumeClaim),  a PV(PersistentVolume) or a storage class?

**Comment by jplu** [comment]
Hi @haorenfsa and thanks a lot for your help.

About the Ingress:
This was my guess but I wanted to be sure, happy that you confirm that. I will continue with the L4 until you publish your piece of doc about it because indeed, I would prefer to pass by the L7 with the gce ingress.

About the persistent storage:
I usually create an SC and a PV with:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClass }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
And:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "project.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: {{ include "project.fullname" . }}
  gcePersistentDisk:
    pdName: {{ .Values.persistence.pdName }}
    fsType: ext4
```
Otherwise, another solution that would fit for me, is to make Milvus reuse the previously created PV. I mean that when I deploy Milvus, several PV are created and the disks as well, but when I destroy the cluster the PVs are destroyed as well but the disks are still there. How to make Milvus able to reuse those that are already there once it is redeployed? And not creating new ones.
