### ISSUE TITLE
Error : too many colons in address (externalS3 url)

### ISSUE THREAD

**Issue by simon-fauconnier** [milvus-io/milvus-helm#400]
Hello, I tried to deploy Milvus with an external S3 but the datacoord throw some error during initialization.
The .yaml configuration work perfectly on the same cluster with the version 3.2.18 of the chart.

```
[2022/12/12 09:15:31.777 +00:00] [ERROR] [datacoord/service.go:129] ["dataCoord init error"] [error="address minio.default.svc.cluster.local:tcp://10.103.159.177:9000: too many colons in address"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:129\ngithub.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:233\ngithub.com/milvus-io/milvus/cmd/components.(*DataCoord).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/data_coord.go:49\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:102"]
```

Helm chart version : 3.3.4

Values:
[config.yaml.txt](https://github.com/milvus-io/milvus-helm/files/10206503/config.yaml.txt)

Datacoord log:
[milvus-datacoord-75b9f77898-cc6bb.log](https://github.com/milvus-io/milvus-helm/files/10206480/milvus-datacoord-75b9f77898-cc6bb.log)

The accessKey and the secretKey have been removed.

**Comment by yanliang567** [comment]
@LoveEachDay could you please help to take a look at this issue?

**Comment by LoveEachDay** [comment]
@simon-fauconnier Could you double check that the host `minio.default.svc.cluster.local` is valid and accessible? 
I've tested the same chart version with an external minio svc, and the cluster will start normally.
```
minio:
  accessKeyID: *******
  address: test-1-minio.test.svc.cluster.local
  bucketName: milvus-bucket
  cloudProvider: aws
  iamEndpoint: null
  port: 9000
  rootPath: file
  secretAccessKey: *******
  useIAM: false
  useSSL: false
```
datacoord log:
```
[2022/12/22 04:22:25.276 +00:00] [INFO] [storage/minio_chunk_manager.go:130] ["minio chunk manager init success."] [bucketname=milvus-bucket] [root=file]
```
