### ISSUE TITLE
Please make spec.rules[].host.http.paths[].path as helm variable

### ISSUE THREAD

**Issue by skspark** [milvus-io/milvus-helm#425]
I'd like to use multiple path setting for single host in ingress,
but currently ingress host path is fixed as "/" in chart: 
https://github.com/milvus-io/milvus-helm/issues/411
```
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $serviceName }}
              port: 
                number: {{ $servicePort }}
```

Would you please consider separating ingress host path variable?
e.g.
```
  {{- range .Values.ingress.hosts }}
  - host: {{ host }}
    http:
      paths:
        - path: {{ path }} 
          pathType: Prefix
          backend:
            service:
              name: {{ $serviceName }}
              port: 
                number: {{ $servicePort }}
```
