### ISSUE TITLE
Unclear Steps for Running Milvus in GKE with GCS Bucket and Enabled Workload Identity

### ISSUE THREAD

**Issue by farioas** [milvus-io/milvus-helm#448]
Hello Milvus Team,

I'm trying to deploy Milvus on Google Kubernetes Engine (GKE) and want to use Google Cloud Storage (GCS) for storing data. In addition, I'm planning to use Google's Workload Identity for service account impersonation.

I have already enabled Workload Identity, and here's the configuration for my service account:
```
serviceAccount:
  create: true
  name: milvus-dev
  annotations:
    iam.gke.io/gcp-service-account: milvus-sa@my-project-666.iam.gserviceaccount.com
```

My first attempt was to disable Minio and use an external S3 bucket for GCS:
```
minio:
  enabled: false
externalS3:
  enabled: true
  useSSL: true
  bucketName: "my-gcs-bucket"
  useIAM: true
  cloudProvider: "gcp" 
```

Unfortunately, it didn't work as expected. Afterward, I found a related issue [hinting](https://github.com/milvus-io/milvus/discussions/17710#discussioncomment-3018179) at the use of standalone Minio mode. Hence, I tried the following configuration:
```
minio:
  enabled: true
  mode: standalone
  useIAM: true
  gcsgateway:
    enabled: true
    projectId: my-project-666

externalGcs:
  bucketName: "my-gcs-bucket"
```

However, this configuration led to an exception from the Milvus subchart, indicating that Gateway mode is deprecated:
```
ERROR Gateway is deprecated, To continue to use Gateway please use releases no later than 'RELEASE.2022-10-24T18-35-07Z'. We recommend all our users to migrate from gateway mode to server mode. Please read https://blog.min.io/deprecation-of-the-minio-gateway/: Invalid arguments specified
```

Okay, I decided to pin the minio image to `RELEASE.2022-10-24T18-35-07Z`, now I get:
```
‘gcs’ is not a minio sub-command. See ‘minio --help’.
```
Describe of minio pod shows this command:
```
    Command:
      /bin/sh
      -ce
      /usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ gateway gcs my-project-666
```

I'm having trouble understanding the correct way to achieve this setup. Could you please clarify how to properly run Milvus in GKE using a GCS bucket with Workload Identity enabled for service account impersonation?

Thanks in advance for your help.

**Comment by haorenfsa** [comment]
Hi! Than you for this feedback. The `useIAM` feature is rarely used only by `milvus-helm` users, so it's not documented yet. You're very close in your first attempt, you just need to set the host and port. And do not enable `gcsgateway`.
```yaml
minio:
  enabled: false
externalS3:
  enabled: true
  host: "storage.googleapis.com"
  port: 443
  useSSL: true
  bucketName: "my-gcs-bucket"
  useIAM: true
  cloudProvider: "gcp"
```
